site_name: Developer Mind Palace
site_description: My personal mind palace that summarizes my knowledge
site_author: Aleksei Mikhalev
site_url: ""
repo_url: https://github.com/AlekseiMikhalev/mind-palace
nav:
  - Introduction: index.md
  - Projects:
      - projects/index.md
      - Book Summarizer:
          - projects/book_summarizer/index.md
      - Age Classification:
          - projects/age_classification/index.md
  - Software Architecture:
      - software_architecture/index.md
      - Architectural Patterns:
          - software_architecture/architectural_patterns/mv_patterns.md
      - Architectural Principles:
          - software_architecture/clean_architecture.md
  - Frontend:
      - frontend/index.md
      - Create a website:
          - create_website.md
  - Backend:
      - backend/index.md
      - Efficient Programming:
          - backend/efficient_programming.md
          - Concurrency and Parallelism:
              - backend/concurrency_parallelism.md
          - OOP:
              - backend/oop.md
          - Testing:
              - backend/testing.md
      - CI/CD Pipeline:
          - ci_cd_pipeline.md
      - Microservice:
          - microservices.md
      - API Gateway:
          - gateway.md
      - Data Center:
          - data_centers.md
      - Load Balancer:
          - load_balancer.md
      - Message Broker:
          - backend/message_broker.md
      - Containers Orchestration:
          - containers_orchestration.md
      - Data Query and Manipulation:
          - data_query.md
      - Database:
          - database.md
      - Storage for Large Files:
          - storage.md
      - Cache:
          - cache.md
      - Text Search:
          - text_search.md
      - Analytics:
          - analytics.md
      - Scheduller:
          - scheduller.md
      - Big Data:
          - big_data.md
  - Machine Learning:
      - machine_learning/index.md
      - Math:
          - machine_learning/math.md
      - NLP:
          - machine_learning/nlp/index.md
          - Text Classification: machine_learning/nlp/text_classification.md
          - Information Search: machine_learning/nlp/information_search.md
          - Statistical Analysis of Text: machine_learning/nlp/statistical_text_analysis.md

plugins:
  - section-index
  - glightbox
  - search:
      lang: en

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  font:
    header: Roboto
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/alekseimikhalev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksmihalev

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
