site_name: Developer Mind Palace
site_description: My personal mind palace that summarizes my knowledge
site_author: Aleksei Mikhalev
site_url: https://alekseimikhalev.github.io
repo_url: https://github.com/alekseimikhalev
nav:
  - Introduction: index.md
  - Projects: projects.md
  - Coding:
      - Learning to code:
          - code_learning.md
          - Frontend developer: frontend_learning.md

plugins:
  - section-index
  - glightbox
  - search:
      lang: en

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  font:
    header: Roboto
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/alekseimikhalev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksmihalev

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
